version: "3"

services:
  xray-server:
    image: xray-server:latest
    environment:
      UUID:
      HOST:
    restart: unless-stopped
    volumes:
     - /var/vless-grpc/caddy:/opt/xray/caddy

  caddy:
    image: caddy:2.7
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - "xray-server"
    restart: unless-stopped
    volumes:
     - /var/vless-grpc/caddy/Caddyfile:/etc/caddy/Caddyfile
     - /var/vless-grpc/caddy:/var/caddy
     - /var/vless-grpc/caddy/data:/data
     - /var/vless-grpc/caddy/config:/config
